{% set name = "dash-bio" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_bio-{{ version }}.tar.gz
  sha256: 6f3717269cde0bbd0ffd5877611ebf6d64b3c1d09d1768aa4ebe3003312e3b67

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - dash >=1.6.1
    - dash-core-components
    - dash-html-components
    - dash-table
    - pandas
    - scipy
    - scikit-learn >=0.20.1
    - biopython >=1.77
    - colour
    - geoparse >=1.1.0
    - jsonschema
    - parmed
    - periodictable
    - requests
    - typing_extensions

test:
  imports:
    - dash_bio
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/plotly/dash-bio
  summary: Dash components for bioinformatics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
